name: 合并链接文件

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 (UTC) 执行

jobs:
  merge_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 创建输出目录
        run: mkdir -p output

      - name: 合并链接
        run: |
          cat << EOF > output/merged_links.yaml
          Gemini: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
          Claude: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
          OpenAI: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
          EOF

      - name: 上传合并后的文件
        uses: actions/upload-artifact@v3
        with:
          name: merged-links
          path: output/merged_links.yaml
